import pytz
from datetime import datetime

timezone = pytz.timezone('Asia/Bangkok')

class UiConfig:
    def __init__(self):
        self.timestamp_string = "<p style='text-align: right;'><small>{}</small></p>"
        self.disclaimer = ("**DISCLAIMER:** This demo uses an Amazon Bedrock foundation model and "
                           "is not intended to collect any personally identifiable information (PII) from users. "
                           "Please do not provide any PII when interacting with this demo. "
                           "The content generated by this demo is for informational purposes only.")
        self.custom_css = """
    <style>
        .text-with-bg {
        color: white;
            background-color: #1c2e4a; /* Change this to your desired background color */
            padding: 10px;
            border-radius: 5px;
        }

        .stSpinner {
            position: fixed;
            bottom: 20px;
            z-index: 10;
        }

        .st-emotion-cache-1ru4d5d, .st-emotion-cache-139wi93 {
            max-width: 70rem;
        }
        .st-emotion-cache-1dp5vir {
            background-image: linear-gradient(90deg, rgb(148, 241, 246), rgb(148, 189, 246));
        }
        .st-emotion-cache-1ghhuty {
            background-color: #87CEEB;
        }
        .st-co, .st-cn, .st-cm, .st-cm {
            border-bottom-color: rgba(28, 131, 225);
            border-top-color: rgba(28, 131, 225);
            border-right-color: rgba(28, 131, 225);
            border-left-color: rgba(28, 131, 225);
        }
        
        .st-emotion-cache-4oy321 {
            padding: 1rem;
        }
    </style>
"""

    def current_time(self):
        user_now = datetime.now(timezone)
        return self.timestamp_string.format(user_now.strftime("%H:%M:%S"))
